name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: server_config

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/docker/web

            if [ -d "FRONTEND" ]; then
              echo "Directory exists. Pulling latest changes."
              cd FRONTEND
              git reset --hard
              git clean -fd
              git checkout DEPLOY
              git pull origin DEPLOY
            else
              echo "Directory does not exist. Cloning repository."
              git clone --branch DEPLOY https://github.com/Y0rFa1se/FRONTEND.git
              cd FRONTEND
            fi

            echo "${{ secrets.DOT_ENV }}" > .env

            if [ -n "$(docker ps -q -f "name=frontend-1")" ]; then
              docker build -t frontend-2 .
              echo "frontend-1 exists"
              docker run -d --restart=always --name frontend-2 -v web:/app/web -p 8002:3000 frontend-2

              while ! curl -s http://192.168.0.18:8002; do
                sleep 5
              done

              docker stop frontend-1 || true
              docker rm frontend-1 || true
              docker rmi frontend-1 || true

            elif [ -n "$(docker ps -q -f "name=frontend-2")" ]; then
              docker build -t frontend-1 .
              echo "frontend-2 exists"
              docker run -d --restart=always --name frontend-1 -v web:/app/web -p 8001:3000 frontend-1

              while ! curl -s http://192.168.0.18:8001; do
                sleep 5
              done

              docker stop frontend-2 || true
              docker rm frontend-2 || true
              docker rmi frontend-2 || true

            else
              docker build -t frontend-1 .
              echo "Neither exists"
              docker run -d --restart=always --name frontend-1 -v web:/app/web -p 8001:3000 frontend-1

            fi